name: MacOs

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Test shell command on MacOs
        run: |
          echo $?
          wgetxy "http://example.com/"
          echo $?
