name: MacOs

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install mpv
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: mpv

      - name: Run mpv
        run: |
          mpv
          
      - name: Install yt-dlp
        run: |
          pip install --upgrade yt-dlp

      - name: Run it
        run: |
          loc=$(which yt-dlp)
          echo $loc
          mpv --script-opts="ytdl_hook-ytdl_path=$loc" --no-audio "https://www.youtube.com/watch?v=VpOLXXBcAl0"
