name: MacOs

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install Package
        uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: mpv
      - name: Test shell command on MacOs
        run: |
          mpv
