name: Test in mpv

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install mpv
      run: |
        sudo add-apt-repository ppa:mc3man/mpv-tests
        sudo apt-get install mpv
    - name: Remove youtube-dl
      run: |
        sudo apt purge youtube-dl
    - name: Install yt-dlp
      run: |
        pip install --upgrade yt-dlp
        yt-dlp --update
    - name: Where is yt-dlp
      run: |
         which yt-dlp
    - name: Configure mpv to use yt-dlp
      run: |
        mkdir -p ~/.config/MPV/
        touch ~/.config/MPV/mpv.conf
        echo -e '\nscript-opts=ytdl_hook-ytdl_path=$loc\n' >> ~/.config/MPV/mpv.conf
    - name: Run it
      run: |
        loc=$(which yt-dlp)
        mpv --script-opts="ytdl_hook-ytdl_path=$loc" "https://www.youtube.com/watch?v=VpOLXXBcAl0"
