name: Test in mpv

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudp apt install mpv -y
    - name: Run it
      run: |
        mpv
